name: atac
channels:
  - conda-forge
  - bioconda

dependencies:
  - bamscale
  - bedops
  - bedtools
  - bioconductor-GenomicRanges
  - bioconductor-TxDb.Hsapiens.UCSC.hg38.knownGene
  - bioconductor-TxDb.Mmusculus.UCSC.mm10.knownGene
  - bioconductor-atacseqqc
  - bioconductor-chippeakanno
  - bioconductor-chipseeker
  - bioconductor-clusterprofiler
  - bioconductor-complexheatmap
  - bioconductor-csaw
  - bioconductor-fgsea
  - bioconductor-ggbio
  - bioconductor-gviz
  - bioconductor-orthology.eg.db
  - bioconductor-rgreat
  - bioconductor-rsamtools
  - bioconductor-ruvseq
  - bioconductor-soggi
  - bowtie2
  - fastp
  - fastqc
  - homer
  - macs2
  - multiqc
  - openpyxl
  - pandas
  - parallel
  - r-ggextra
  - r-ggpattern
  - r-ggrepel
  - r-ggsci
  - r-magick
  - r-msigdbr
  - r-tidyverse
  - r-tidyverse
  - r-yaml
  - samtools
  - snakemake