
atac_container: "/home/jeszyman/sing_containers/atac.1.1.0.sif"
atac_repo: "/home/jeszyman/repos/atac-seq"
autosome_bed: "/home/jeszyman/repos/atac-seq/test/inputs/mm10chrs.bed"
blacklist_bed: "/home/jeszyman/repos/atac-seq/test/inputs/mm10-blacklist.v2.bed"

#conda_environment: "/home/jeszyman/repos/atac-seq/config/atac_env.yaml"

data_dir: "/mnt/ris/szymanski/Active/test"
genome_fasta: "/mnt/ris/szymanski/Active/test/inputs/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
threads: 4


# Common names across repositories and snakefiles

gsize: "1.87e9"


# Repository and snakefile-specific names
container:
  atac: "~/sing_containers/atac.1.1.0.sif"
scriptdir:
  atac: "workflow/scripts"

atac_keep_bed: "resources/keep.bed"

gtf: "test/inputs/chr19.gtf"

# Directories
##
## Common
data_dir: "/mnt/ris/szymanski/Active/test"
log_dir: "test/logs"
qc_dir: "test/qc"
##
## ATAC-seq
dir:
  atac_fastq_raw: "test/fastq-atac-raw"
  atac_fastq_proc: "test/fastq-atac-proc"
