container: "~/sing_containers/atac.sif"
threads: 4
bam_dir: "test/bam"
bowtie_prefix: "test/inputs/ucsc_mm10_chr19/ucsc_mm10_chr19"
keep_bed: "resources/keep.bed"
log_dir: "test/logs"
qc_dir: "test/qc"
atac_scripts_dir: "workflow/scripts"
dca_dir: "test/dca"
data_dir: "test"
fq_sym_dir: "test/fastq"
fq_src_dir: "test/inputs"