# Common names across repositories and snakefiles
datadir: "test"
fasta: "test/inputs/chr19.fa"
logdir: "test/logs"
threads: 4

# Repository and snakefile-specific names
container:
  atac: "~/sing_containers/atac.1.1.0.sif"
scriptdir:
  atac: "workflow/scripts"

keep_bed: "resources/keep.bed"

gtf: "test/inputs/chr19.gtf"